Added a project with unit tests.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -25,22 +25,22 @@ NC='\033[0m' # No Color
 
     ## navigate to the test project to run the tests
     ## TODO: change this to your test project directory
-    #cd test
-    #
-    #echo -e "${YELLOW}Running unit tests...${NC}"
-    #echo ""
-    #
-    ## run the unit tests
-    #dotnet test
-    #
-    ## $? is a shell variable which stores the return code from what we just ran
-    #rc=$?
-    #if [[ $rc != 0 ]] ; then
-    #    # A non-zero return code means an error occurred, so tell the user and exit
-    #    echo -e "${RED}Unit tests failed, please fix and push again${NC}"
-    #    echo ""
-    #    exit $rc
-    #fi
+    cd Survey.Business.XUnit.Test
+    
+    echo -e "${YELLOW}Running unit tests...${NC}"
+    echo ""
+    
+    # run the unit tests
+    dotnet test
+    
+    # $? is a shell variable which stores the return code from what we just ran
+    rc=$?
+    if [[ $rc != 0 ]] ; then
+        # A non-zero return code means an error occurred, so tell the user and exit
+        echo -e "${RED}Unit tests failed, please fix and push again${NC}"
+        echo ""
+        exit $rc
+    fi
 
     # Everything went OK so we can exit with a zero
     echo -e "${GREEN}Pre push check passed!${NC}"
