fixed.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -28,12 +28,12 @@ NC='\033[0m' # No Color
 	
 	for unitTestProjectDirectory in "${unitTestProjectDirectories[@]}"
 	do
-		echo "$i"
+		echo -e "$unitTestProjectDirectory"
 		## navigate to the test project to run the tests
 		## TODO: change this to your test project directory
-		echo %%unitTestProjectDirectory
+		#echo %%unitTestProjectDirectory
 		
-		cd %%unitTestProjectDirectory
+		cd $unitTestProjectDirectory
 		
 		echo -e "${YELLOW}Running unit tests...${NC}"
 		echo ""
@@ -56,29 +56,29 @@ NC='\033[0m' # No Color
 
 	#set unitTestProjectDirectories = Survey.Business.XUnit.Test
 	
-	for %%unitTestProjectDirectory in %unitTestProjectDirectories%
-	do 
-		## navigate to the test project to run the tests
-		## TODO: change this to your test project directory
-		echo %%unitTestProjectDirectory
-		
-		cd %%unitTestProjectDirectory
-		
-		echo -e "${YELLOW}Running unit tests...${NC}"
-		echo ""
-		
-		# run the unit tests
-		dotnet test
-		
-		# $? is a shell variable which stores the return code from what we just ran
-		rc=$?
-		if [[ $rc != 0 ]] ; then
-			# A non-zero return code means an error occurred, so tell the user and exit
-			echo -e "${RED}Unit tests failed, please fix and push again${NC}"
-			echo ""
-			exit $rc
-		fi
-	done
+	#for %%unitTestProjectDirectory in %unitTestProjectDirectories%
+	#do 
+	#	## navigate to the test project to run the tests
+	#	## TODO: change this to your test project directory
+	#	echo %%unitTestProjectDirectory
+	#	
+	#	cd %%unitTestProjectDirectory
+	#	
+	#	echo -e "${YELLOW}Running unit tests...${NC}"
+	#	echo ""
+	#	
+	#	# run the unit tests
+	#	dotnet test
+	#	
+	#	# $? is a shell variable which stores the return code from what we just ran
+	#	rc=$?
+	#	if [[ $rc != 0 ]] ; then
+	#		# A non-zero return code means an error occurred, so tell the user and exit
+	#		echo -e "${RED}Unit tests failed, please fix and push again${NC}"
+	#		echo ""
+	#		exit $rc
+	#	fi
+	#done
 
 
 	#for unitTestProjectDirectory in unitTestProjectDirectories
